### ISSUE TITLE
[Issue]reforge16 has a large size jar after compiled

### ISSUE THREAD

**Issue by Lileep** [EnvyWare/API#11]
reforged16 mod has 76Mb after compiling via `reobjShadowJar` task, but forge16 doesn't have the same issue, it has only 3Mb after compiled.

This issue makes the shadow plugin shadow dependencies like minecraft and pixelmon, then let mods depend on reforged16 has a large size up to 90+Mb. Have seen sth about the exclude function from shadow doc, but it doesn't work, too.

Following is a file list inside the compiled reforged16 jar, most files are things from Minecraft and forge:
![image](https://user-images.githubusercontent.com/103249400/171075569-aa2595ec-3539-4c3e-b30e-2ea17f6edfb4.png)

**Comment by danorris709** [comment]
You're compiling the API?

**Comment by Lileep** [comment]
> You're compiling the API?

Not just the API. When I'm compiling my mod(used API 2.4.8) via `reobfShadowJar` task, the gradle packs all the dependencies into itself, including the code of vanilla mc and pixelmon.
Now I've tried to change the `build.gradle` of my mod to fit API 2.5.4 and it finally works. Thanks for ur great work. :)

**Comment by Lileep** [comment]
Now I'm facing with another issue. The hikari part in API seems to be broken when I view the source.

![image](https://user-images.githubusercontent.com/103249400/175055449-e6d14216-033e-47b5-b56b-8a078be032e5.png)

Though things can work well when starting a server, it logs error when loading database source:
```
[com.github.lileep.pixelmonbank.shade.slf4j.impl.SimpleLogger:write:381]: [envyware_concurrency_0] INFO com.github.lileep.pixelmonbank.shade.hikari.hikari.HikariDataSource - pixelmon-bank-pool - Starting...
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/pixelbank
 	at com.github.lileep.pixelmonbank.shade.hikari.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
 	at com.github.lileep.pixelmonbank.shade.hikari.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
 	at com.github.lileep.pixelmonbank.shade.hikari.hikari.pool.PoolBase.<init>(PoolBase.java:114)
 	at com.github.lileep.pixelmonbank.shade.hikari.hikari.pool.HikariPool.<init>(HikariPool.java:108)
 	at com.github.lileep.pixelmonbank.shade.hikari.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
 	at com.github.lileep.pixelmonbank.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:65)
 	at com.github.lileep.pixelmonbank.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:22)
	at com.github.lileep.pixelmonbank.PixelmonBank.lambda$preInit$0(PixelmonBank.java:78)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 	at java.lang.Thread.run(Unknown Source)
 Caused by: java.sql.SQLException: No suitable driver
 	at java.sql.DriverManager.getDriver(Unknown Source)
 	at com.github.lileep.pixelmonbank.shade.hikari.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
 	... 10 more
```

There's nothing wrong with the sql connection. Hope that there're solutions.

**Comment by danorris709** [comment]
Make sure you've not toggled the transitive to false for commons
